services:
  wuzapi:
    image: asternic/wuzapi:latest
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    entrypoint: /bin/sh -c "./wuzapi | tee -a /app/logs/wuzapi.log"
    volumes:
      - ./wuzapi_data:/app/dbdata
      - ./logs/:/app/logs
    environment:
      - WUZAPI_ADMIN_TOKEN=${ADMIN_TOKEN}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - WUZAPI_PORT=8080
      - WUZAPI_GLOBAL_ENCRYPTION_KEY=${WUZAPI_GLOBAL_ENCRYPTION_KEY}
      - WUZAPI_GLOBAL_HMAC_KEY=${WUZAPI_GLOBAL_HMAC_KEY}
      - TZ=Asia/Jerusalem

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "127.0.0.1:5672:5672"   # Messaging port
      - "127.0.0.1:15672:15672" # Dashboard (optional)
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq #save queue in case of container dies
    environment:
      - TZ=Asia/Jerusalem

  logic_engine:
    build: ./code
    container_name: logic_engine  
    volumes:
      - ./code:/app/
      - ./logs:/var/log/logic
    restart: always
    depends_on:
      - rabbitmq
      - wuzapi
    env_file:
      - .env


  diun:
    image: crazymax/diun:latest
    restart: always
    command: serve
    volumes:
      - "./diun_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Asia/Jerusalem"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=1"
      - "DIUN_WATCH_SCHEDULE=0 */3 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=https://discord.com/api/webhooks/1549689212146548786/HjQ_qmG5DA0XooyKJJI39hKwMA2tSeGff9_f4AnvG3_qe9ZE-KP9kSHOKPFqsMrcrLL9"
      - "DIUN_NOTIF_DISCORD_MENTIONS=@everyone"
    labels:
      - "diun.enable=true"
